### ISSUE TITLE
Login does not work with user that has not been stored in the keychain previously

### ISSUE THREAD

**Issue by ghost** [andinfinity/idrop.link-osx#35]
Related error log: 

> 22/08/15 19:54:01,808 secd[18789]:  securityd_xpc_dictionary_handler idrop.link[29242] delete The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
> 22/08/15 19:54:01,808 idrop.link[29242]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

**Comment by ChristianSch** [comment]
This has nothing to do with the logged output (it is always being printed!) but rather with issue #34. Closing because of redundancy.
