### ISSUE TITLE
automatically upload screenshots

### ISSUE THREAD

**Issue by ChristianSch** [andinfinity/idrop.link-osx#40]
see: https://www.quora.com/How-do-you-intercept-screenshots-in-OS-X-like-Dropbox-screenshot-sync

**Comment by ChristianSch** [comment]
proposed solution: check for `~/Library/Preferences/com.apple.screencapture.plist`, if not existing, default to `~/Desktop` (or whatever localized value this is). Subscribe for changes, if fchanges occured, upload.

**Comment by DanielSeemaier** [comment]
I implemented a solution based on this SO answer: http://stackoverflow.com/a/5685024 and pushed it to branch screenshot-integration. 

While the code seems to work, someone should probably clean it up before merging it with master.

**Comment by ChristianSch** [comment]
Remaining action items:
- [x] implement corresponding preference window settings
- [x] check the preferences before uploading any screenshots (maybe even before registering the listener)
